cargo-features = ["edition2024"]

[package]
name = "poster_reader"
version = "0.1.0"
edition = "2024"
author = "Jaganath_Gajendran"

[dependencies]
image = "0.25.1"
tesseract = "0.15.1"
anyhow = "1.0.56"
log = "0.4.14"
env_logger = "0.11.3"
rust_xlsxwriter = "0.64.2"
